DjangoProjects/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from DjangoProjects.settings import MEDIA_URL

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('to_do_app.urls', namespace='to_do_app')),
    path('weather/', include('weather.urls', namespace='weather')),

]

to_do_app/urls.py
from django.urls import path
from to_do_app.views import show_todo_active, show_todo_completed, login, register, logout, add_todo, delete_todo, edit_todo, check_todo, clear_completed_todos

app_name = 'to_do_app'
urlpatterns = [
    # path('all/', show_todo_all, name='show_todo_all'),
    path('active/', show_todo_active, name='show_todo_active'),
    path('completed/', show_todo_completed, name='show_todo_completed'),
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout, name='logout'),
    path('add_todo/', add_todo, name='add_todo'),
    path('check_todo/<int:todo_id>/<str:todo_status>', check_todo, name='check_todo'),
    path('edit_todo/<int:todo_id>', edit_todo, name='edit_todo'),
    path('delete_todo/<int:todo_id>', delete_todo, name='delete_todo'),
    path('clear_completed_todos/', clear_completed_todos, name='clear_completed_todos'),
]

weather/urls.py
from django.urls import path
from weather.views import index

app_name = 'weather'
urlpatterns = [
    path('', index, name='index'),

]

to_do_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Todo(models.Model):
    title = models.CharField(max_length=30)
    date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(choices=(('active', 'active'), ('completed', 'completed')), max_length=10, default='active')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.title

weather/models.py
from django.db import models

# Create your models here.

to_do_app/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.contrib.auth.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-input', 'placeholder': 'Password'}))
    class Meta:
        model = User
        fields = ('username', 'password')

class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Username'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-input', 'placeholder': 'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-input', 'placeholder': 'Confirm Password'}))
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

to_do_app/views.py
from django.shortcuts import render, redirect
from django.contrib import auth


from to_do_app.models import Todo
from to_do_app.forms import UserLoginForm, UserRegistrationForm
from django.contrib.auth.decorators import login_required

# Create your views here.
# @login_required
# def show_todo_all(request):
#     todo_titles = Todo.objects.filter(user=request.user).order_by('-date')
#     context = {
#         'title': 'Todo\'s',
#         'todo_titles': todo_titles
#     }
#     return render(request, 'weather.html', context)

@login_required
def show_todo_active(request):
    todo_titles = Todo.objects.filter(user=request.user, status='active').order_by('-date')
    context = {
        'title': 'Active Todo\'s',
        'quantity': todo_titles.count(),
        'todo_titles': todo_titles
    }
    return render(request, 'index.html', context)

@login_required
def show_todo_completed(request):
    todo_titles = Todo.objects.filter(user=request.user, status='completed').order_by('-date')
    context = {
        'title': 'Completed Todo\'s',
        'quantity': todo_titles.count(),
        'todo_titles': todo_titles
    }
    return render(request, 'index.html', context)

@login_required
def check_todo(request, todo_id, todo_status):
    new_todo_status = 'completed' if todo_status=='active' else 'active'
    Todo.objects.filter(id=todo_id, user=request.user).update(status=new_todo_status)
    return redirect(request.META['HTTP_REFERER'])

def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return redirect('to_do_app:show_todo_active')
    else:
        form = UserLoginForm()
    context = {
        'title': 'Login',
        'form': form,

    }
    return render(request, 'login.html', context)

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('to_do_app:login')
    else:
        form = UserRegistrationForm()

    context = {
        'title': 'Register',
        'form': form,
    }
    return render(request, 'signup.html', context)

@login_required
def logout(request):
    auth.logout(request)
    return redirect('to_do_app:login')

@login_required
def add_todo(request):

    title = request.POST['new_todo_input']
    obj = Todo.objects.create(title=title, user=request.user)
    obj.save()
    return redirect('to_do_app:show_todo_active')

@login_required
def edit_todo(request, todo_id):
    title = request.POST['edit_todo_input']
    Todo.objects.filter(id=todo_id, user=request.user).update(title=title)
    return redirect(request.META['HTTP_REFERER'])

@login_required
def delete_todo(request, todo_id):
    todo = Todo.objects.get(pk=todo_id)
    todo.delete()
    return redirect(request.META['HTTP_REFERER'])

@login_required
def clear_completed_todos(request):
    Todo.objects.filter(user=request.user, status='completed').delete()
    return redirect(request.META['HTTP_REFERER'])

weather/views.py
from datetime import datetime
from re import search
from turtledemo.penrose import start

from django.conf import settings
from django.shortcuts import render
import requests
from pyexpat.errors import messages


# Create your views here.
def index(request):
    location = 'Moscow'
    if 'location_input' in request.POST:
        location = request.POST['location_input']
    open_weather_url = f'https://api.openweathermap.org/data/2.5/weather?q={location}&appid=bcab89ad8807c1e58030b852f013ab28&units=metric'
    image_url = ''
    try:
        SEARCH_API = ''
        SEACH_ENGINE_ID = ''
        query = location + ' 1920x1080'
        location_url = f'https://www.googleapis.com/customsearch/v1?key={SEARCH_API}&cx={SEACH_ENGINE_ID}&q={query}&searchType=image'
        data = requests.get(location_url).json()
        search_items = data.get('items')
        for item in search_items:
            access = requests.get(item['link']).status_code
            if access==200:
                image_url = item['link']
                break
            else:
                continue    
        
    except Exception as e:
        print(f'Ошибка google: {e}')
        
    try:

        data = requests.get(open_weather_url).json()

        context = {
            'location': location,
            'description': data['weather'][0]['description'],
            'temp': data['main']['temp'],
            'humidity': data['main']['humidity'],
            'pressure': data['main']['pressure'],
            'icon': data['weather'][0]['icon'],
            'wind': data['wind']['speed'],
            'feels_like': data['main']['feels_like'],
            'datetime': datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            'image_url': image_url,
            
        }
        return render(request, 'weather.html', context)
    except Exception as e:
        print(f'Ошибка: {e}')
        context = {
            'location': location,
            'description': '',
            'temp': '',
            'humidity': '',
            'pressure': '',
            'icon': '01d',
            'wind': '',
            'feels_like': '',
            'datetime': datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            'image_url': image_url,
            
        }
        return render(request, 'weather.html', context)

to_do_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="author" content="Hari Ram"/>
    <title>{{ title }}</title>


    <link
            rel="icon"
            type="image/png"
            sizes="32x32"
            href="{% static 'todo/assets/images/favicon-32x32.png' %}"
    />

    <link rel="preconnect" href="https://fonts.gstatic.com"/>
    <link
            href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@400;700&display=swap"
            rel="stylesheet"
    />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,200,0,-25&icon_names=save"/>
    {% block css %}
        <link rel="stylesheet" href="{% static 'todo/css/styles.css' %}"/>
    {% endblock %}

    <link rel="preload" href="{% static 'todo/assets/images/icon-check.svg' %}" as="image" type="image/svg+xml" crossorigin="anonymous">
</head>
<body>
<header class="card">
    <h1>TODO</h1>
    <form action="{% url 'to_do_app:logout' %}" method="post" >
        {% csrf_token %}
        <button id="theme-switcher" type="submit">
            <svg xmlns="http://www.w3.org/2000/svg" height="40px" viewBox="0 -960 960 960" width="40px" fill="#ffffff">
                <path d="M219.69-161.41q-23.41 0-40.14-16.73t-16.73-40.32v-521.67q0-23.59 16.73-40.32t40.14-16.73H480.9v32.44H219.87q-9.23 0-16.92 7.69-7.69 7.69-7.69 16.92v521.67q0 9.23 7.69 16.92 7.69 7.69 16.92 7.69H480.9v32.44H219.69ZM666.28-348.6l-23.63-22.27 92.21-92.21H368.54v-32.43h366.01l-92.2-92.21 23.11-23.5 131.72 131.98-130.9 130.64Z"/>
            </svg>
        </button>
    </form>

</header>
{% block content %}

{% endblock %}
{#    <script src="{% static 'todo/js/scripts.js' %}"></script>#}
</body>
</html>

to_do_app/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'todo/css/styles.css' %}"/>
    <script src="https://kit.fontawesome.com/0e9700bd22.js" crossorigin="anonymous"></script>
    <style>
        .txt-container-edit {
            flex: 1;
        }

        .txt-input-edit {
            width: 100%;
            padding: 0.7rem 0;
            color: var(--clr-gb-1);
        }

        body.light .txt-input-edit {
            font-weight: var(--fw-bold);
        }

        .txt-input-edit::placeholder {
            color: var(--clr-gb-5);
            font-weight: var(--fw-normal);
        }

        .todo-edit-form {
            width: 100%;
            display: flex;
            gap: 1rem;
            align-items: center;
        }

        .todo-edit-buttons {
            display: flex;
            gap: 1rem;
            align-items: center;
        }

        .invisible {
            display: none;
        }

        .highlight {
            border: 2px solid #4CAF50;
            padding: 5px;
            border-radius: 5px;
            margin-top: 5px;
        }

    </style>
{% endblock %}
{% block content %}

    <main>
        <form method="post">
            {% csrf_token %}
            <div class="card add">
                <div class="cb-container">
                    <button id="add-btn" type="submit" formaction="{% url 'to_do_app:add_todo' %}">+</button>
                </div>
                <div class="txt-container">
                    <label for="add_new_title">Create todo</label>
                    <input required
                           type="text"
                           class="txt-input"
                           placeholder="Create a new todo..."
                           id="add_new_title"
                           name="new_todo_input"
                    />
                </div>
            </div>
        </form>
        <ul class="todos all">
            {% for todo_title in todo_titles %}
                <li class="card">
                    <form>
                        {% csrf_token %}
                        <div class="cb-container">
                            <input class="cb-input" formaction="{% url 'to_do_app:check_todo' todo_title.id todo_title.status %}" formmethod="post" type="submit">
                            <span class="check"></span>
                        </div>
                    </form>

                    <p class="item">{{ todo_title }}</p>
                    <form class="todo-edit-form invisible">
                        {% csrf_token %}
                        <div class="txt-container-edit">
                            <label for="edit_title">Create todo</label>
                            <input required
                                   type="text"
                                   class="txt-input-edit"
                                   placeholder="Edit todo..."
                                   id="edit_title"
                                   name="edit_todo_input"
                            />
                        </div>
                        <button class="todo-edit-save clear invisible" about="save" type="submit" formmethod="post" formaction="{% url 'to_do_app:edit_todo' todo_title.id %}">
                            <svg xmlns="http://www.w3.org/2000/svg" height="32px" viewBox="0 -960 960 960" width="32px" fill="#494c6b">
                                <path d="M797.46-662.64v443.19q0 23.45-16.73 40.18t-40.14 16.73H219.41q-23.41 0-40.14-16.73t-16.73-40.14v-521.18q0-23.41 16.73-40.14t40.18-16.73h443.19l134.82 134.82Zm-32.43 13.86L648.78-765.03H219.59q-10.77 0-17.69 6.93-6.93 6.92-6.93 17.69v520.82q0 10.77 6.93 17.69 6.92 6.93 17.69 6.93h520.82q10.77 0 17.69-6.93 6.93-6.92 6.93-17.69v-429.19ZM479.84-302.23q30.22 0 51.83-21.46 21.61-21.45 21.61-51.67 0-30.21-21.45-51.82-21.46-21.61-51.67-21.61-30.22 0-51.83 21.45-21.61 21.46-21.61 51.67t21.45 51.83q21.46 21.61 51.67 21.61ZM270.08-576.8h293.56v-113.12H270.08v113.12Zm-75.11-71.98v453.81V-765.03v116.25Z"/>
                            </svg>

                        </button>
                        <button class="todo-edit-cancel clear invisible" about="close">
                            <svg xmlns="http://www.w3.org/2000/svg" height="36px" viewBox="0 -960 960 960" width="36px" fill="#494c6b">
                                <path d="m254.74-231.49-22.97-23.25L456.74-480 231.77-705.26l22.97-23.25L480-503.26l225.26-225.25 22.97 23.25L503.26-480l224.97 225.26-22.97 23.25L480-456.74 254.74-231.49Z"/>
                            </svg>

                        </button>

                    </form>


                    <button name="todo-edit-btn" class="todo-edit clear" about="edit">
                        <svg xmlns="http://www.w3.org/2000/svg" height="30px" viewBox="0 -960 960 960" width="30px" fill="#494c6b">
                            <path d="M219.41-162.54q-23.41 0-40.14-16.73t-16.73-40.14v-521.18q0-23.41 16.73-40.14t40.32-16.73h349.18l-32.44 32.43H219.59q-9.23 0-16.92 7.7-7.7 7.69-7.7 16.92v520.82q0 9.23 7.7 16.92 7.69 7.7 16.92 7.7h520.82q9.23 0 16.92-7.7 7.7-7.69 7.7-16.92v-322.14l32.43-32.44v354.58q0 23.59-16.73 40.32t-40.14 16.73H219.41ZM480-480Zm-78.94 78.94v-103.27l362.73-363.44q4.61-4.23 10.5-6.37 5.89-2.13 12.75-2.13 6.03 0 11.9 2.02 5.86 2.02 11.07 6.39l53.35 52.76q5.7 5.11 8.42 11.91 2.72 6.8 2.72 13.62 0 6.81-2.34 12.95-2.34 6.13-7.25 10.75L500.49-401.06h-99.43Zm441.08-387.71-54-57.32 54 57.32ZM433.5-433.5h53.9l273.27-273.77-26.8-27.13-29.14-27.65L433.5-491.47v57.97Zm300.37-300.9-29.14-27.65 29.14 27.65 26.8 27.13-26.8-27.13Z"/>
                        </svg>

                    </button>


                    <form class="todo-delete">
                        {% csrf_token %}
                        <button type="submit" formaction="{% url 'to_do_app:delete_todo' todo_title.id %}" formmethod="post" class="clear" about="delete">
                            <svg xmlns="http://www.w3.org/2000/svg" height="30px" viewBox="0 -960 960 960" width="30px" fill="#494c6b">
                                <path d="M299.46-162.82q-23.33 0-40.19-16.86t-16.86-40.19v-508.51h-39.87v-32.2h154.13v-27.37h246.95v27.13h154.12v32.44h-39.87v508.69q0 23.41-16.73 40.14t-40.32 16.73H299.46Zm385.98-565.56H274.85v508.51q0 10.77 7.18 17.69 7.17 6.92 17.43 6.92h361.36q9.23 0 16.92-7.69 7.7-7.69 7.7-16.92v-508.51ZM395.82-277.14h32.44v-370.74h-32.44v370.74Zm136.21 0h32.43v-370.74h-32.43v370.74ZM274.85-728.38v533.12-533.12Z"/>
                            </svg>

                        </button>
                    </form>

                </li>
            {% endfor %}


        </ul>
        <div class="card stat">
            <p class="corner"><span id="items-left">{{ quantity }}</span> items left</p>
            <form method="post">
                {% csrf_token %}
                <div class="filter">
                    {#                    <button id="all" type="submit" formaction="{% url 'to_do_app:show_todo_all' %}" >All</button>#}
                    <button id="active" type="submit" formaction="{% url 'to_do_app:show_todo_active' %}">Active</button>
                    <button id="completed" type="submit" formaction="{% url 'to_do_app:show_todo_completed' %}">Completed</button>
                </div>
            </form>
            <form method="post">
                {% csrf_token %}
                <div class="corner">
                    <button id="clear-completed" type="submit" formaction="{% url 'to_do_app:clear_completed_todos' %}">Clear Completed</button>
                </div>
            </form>

        </div>
    </main>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            
            const todoItems = document.querySelectorAll("li.card");

            todoItems.forEach((item) => {
                const editBtn = item.querySelector(".todo-edit");
                const saveBtn = item.querySelector(".todo-edit-save");
                const cancelBtn = item.querySelector(".todo-edit-cancel");
                const deleteBtn = item.querySelector(".todo-delete");
                const editForm = item.querySelector(".todo-edit-form");
                const editInput = editForm.querySelector(".txt-input-edit");
                const todoText = item.querySelector(".item");
                const cbContainer = item.querySelector('.cb-container')

                editBtn.addEventListener("click", () => {
                    // Переносим текущий текст в поле редактирования
                    editInput.value = todoText.textContent;

                    // Показываем форму редактирования и кнопки сохранить/отменить
                    editForm.classList.remove("invisible");
                    saveBtn.classList.remove("invisible");
                    cancelBtn.classList.remove("invisible");
                    cbContainer.classList.remove('cb-container')
                    saveBtn.classList.remove('clear')
                    cancelBtn.classList.remove('clear')
                    // Скрываем кнопки редактировать и удалить
                    editBtn.classList.add("invisible");
                    deleteBtn.classList.add("invisible");
                    todoText.classList.add("invisible")
                    cbContainer.classList.add('invisible')

                    // Добавляем стили для выделения формы
                    editInput.classList.add("highlight");
                    editInput.focus();
                });

                cancelBtn.addEventListener("click", (event) => {
                    event.preventDefault();
                    // Скрываем форму редактирования и кнопки сохранить/отменить
                    editForm.classList.add("invisible");
                    saveBtn.classList.add("invisible");
                    cancelBtn.classList.add("invisible");
                    cbContainer.classList.add("cb-container")

                    // Показываем кнопки редактировать и удалить
                    cbContainer.classList.remove("invisible")
                    todoText.classList.remove("invisible")
                    editBtn.classList.remove("invisible");
                    deleteBtn.classList.remove("invisible");

                    // Убираем стили выделения формы
                    editInput.classList.remove("highlight");
                });
            });
        });


    </script>
{% endblock %}

to_do_app/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
	<link rel="stylesheet" href="{% static 'todo/css/styles.css' %}" />
{% endblock %}
{% block content %}
	<style>
    .form-title{
        color: var(--clr-gb-1);
    }
    .input-form{
        display: flex;
        flex-direction: column;
        align-items: stretch;
    }
    .form-input{
        width: 100%;
        padding: 1rem 1rem;
        color: var(--clr-gb-1);
    }
    .txt-container{
        border: 1px solid white;
        border-radius: 0.5rem;

    }
    .form-btn{
        cursor: pointer;
        border: 1px solid var(--clr-gb-5);
        border-radius: 0.7rem;
        padding: 1rem;
        justify-content: center;
        color: var(--clr-gb-1);
        
    }
    .form-btn:hover{
        background-color: var(--clr-gb-5);
    }
    .sign-up{
        display: flex;
        justify-content: center;
    }
    .sign-up a{
        color: var(--clr-gb-4);
        text-decoration: none;
    }
    .sign-up a:hover{
        color: var(--clr-primary);
    }
    
    </style>

        <form action="{% url 'to_do_app:login' %}" method="post">
            {% csrf_token %}
            <div class="card add input-form">
                <h3 class="form-title">Login Form</h3>
                <div class="txt-container">
                    <label for="{{ form.username.id_for_label }}">Login</label>
                    {{ form.username }}
                </div>
                <div class="txt-container">
                    <label for="{{ form.password.id_for_label }}">Password</label>
                    {{ form.password }}
                </div>
                <button class="form-btn" type="submit">Login</button>
                <div class="sign-up">
                    <a href="{% url 'to_do_app:register' %}">Don't have an account? Sign Up</a>
                </div>
                
            </div>
        </form>


{% endblock %}

to_do_app/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
	<link rel="stylesheet" href="{% static 'todo/css/styles.css' %}" />
    <style>
    .form-title{
        color: var(--clr-gb-1);
    }
    .input-form{
        display: flex;
        flex-direction: column;
        align-items: stretch;
    }
    .form-input{
        width: 100%;
        padding: 1rem 1rem;
        color: var(--clr-gb-1);
    }
    .txt-container{
        border: 1px solid white;
        border-radius: 0.5rem;

    }
    .form-btn{
        cursor: pointer;
        border: 1px solid var(--clr-gb-5);
        border-radius: 0.7rem;
        padding: 1rem;
        justify-content: center;
        color: var(--clr-gb-1);
        
    }
    .form-btn:hover{
        background-color: var(--clr-gb-5);
    }
    .sign-up{
        display: flex;
        justify-content: center;
    }
    .sign-up a{
        color: var(--clr-gb-4);
        text-decoration: none;
    }
    .sign-up a:hover{
        color: var(--clr-primary);
    }
    
    </style>
{% endblock %}
{% block content %}
	

        <form action="{% url 'to_do_app:register' %}" method="post">
            {% csrf_token %}
            <div class="card add input-form">
                <h3 class="form-title">Sign Up Form</h3>
                <div class="txt-container">
                    <label for="{{ form.username.id_for_label }}">Login</label>
                    {{ form.username }}
                </div>
                <div class="txt-container">
                    <label for="{{ form.password1.id_for_label }}">Password</label>
                    {{ form.password1 }}
                </div>
                <div class="txt-container">
                    <label for="{{ form.password2.id_for_label }}">Password</label>
                    {{ form.password2 }}
                </div>
                <button class="form-btn" type="submit">Sign Up</button>
                <div class="sign-up">
                    <a href="{% url 'to_do_app:login' %}">Already have an account? Sign In</a>
                </div>
                
            </div>
        </form>


{% endblock %}

weather/templates/weather.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Let's check this out.
    I will be changing the tab title.-->
    <link rel="stylesheet" href="{% static 'weather/styles.css' %}">
    <title>Weather App</title>
</head>
<!--only added that style part to be able to see the stuff. I will fix
it later in the video where it shows the CSS part.-->
<body>


<div class="weatherPart">
    <div class="inputWeatherPart">
        <form class="inputWeatherPartForm" action="{% url 'weather:index' %}" method="post">
            {% csrf_token %}
            <input class="input-input" type="text" name="location_input" placeholder="Еnter the city">
            <button class="input-btn" type="submit">Search</button>
        </form>
    </div>
    
    <div class="innerWeatherPart" 
        {% if image_url %}
            style='background-image: url({{ image_url }});'
        {% else %}
            style='background-image: url({% static "weather/assets/boat.jpg" %});'
        {% endif %}>

        <div class="topWeatherPart">
            <div class="date" id="theDate">
                {{ datetime }}
            </div>
            <div class="location">
                <img src="{% static 'weather/assets/outline-navigation-location.svg' %}" alt="Location Icon">
                <span id="locationDestination">{{ location }}</span>
            </div>

        </div>
        <div class="bottomWeatherPart">
            <span class="temperature"><span id="highTemp">{{ temp }}</span> °C </span>
            <span class="condition"><img src="https://openwethermap.org/img/w/{{ icon }}.png" width="50px" alt=""></span>
            <span class="condition" id="condition">{{ description }}</span>
            <div class="weatherFeelsPressure">
                <div class="weatherFPWords spaceHere" style="margin-bottom: 10px;">
                    <span><b>Feels Like</b></span>
                    <span id="feels">{{ feels_like }}</span>
                    <span><b>Pressure</b></span>
                    <span id="pressureValue">{{ pressure }}</span>
                </div>
            </div>
            <div class="weatherFPWords2 spaceHere" style="margin-bottom: 15px;">
                <span><b>Humidity</b></span>
                <span><span class="value " id="humidity">{{ humidity }}</span> %</span>
                <span><b>Wind</b></span>
                <span class="value " id="theWind">{{ wind }}</span>

            </div>
        </div>
    </div>


</div>


{#    <script src="{% static 'weather/index.js' %}"></script>#}
</body>
</html>